//
// DO NOT EDIT
//
// Generated by swift-atproto
//
// swift-format-ignore-file

import SwiftAtproto

public enum UnknownATPValue: UnknownATPValueProtocol {
  case record(any ATProtoRecord)
  case any(any Codable & Hashable & Sendable)

  public static let allTypes: [String: any ATProtoRecord.Type] = [
    "app.bsky.actor.contentVisibilityDeclaration": App.Bsky.ActorContentVisibilityDeclaration.self,
    "app.bsky.actor.profile": App.Bsky.ActorProfile.self,
    "app.bsky.actor.status": App.Bsky.ActorStatus.self,
    "app.bsky.feed.generator": App.Bsky.FeedGenerator.self,
    "app.bsky.feed.like": App.Bsky.FeedLike.self,
    "app.bsky.feed.post": App.Bsky.FeedPost.self,
    "app.bsky.feed.postgate": App.Bsky.FeedPostgate.self,
    "app.bsky.feed.repost": App.Bsky.FeedRepost.self,
    "app.bsky.feed.threadgate": App.Bsky.FeedThreadgate.self,
    "app.bsky.graph.block": App.Bsky.GraphBlock.self,
    "app.bsky.graph.follow": App.Bsky.GraphFollow.self,
    "app.bsky.graph.list": App.Bsky.GraphList.self,
    "app.bsky.graph.listblock": App.Bsky.GraphListblock.self,
    "app.bsky.graph.listitem": App.Bsky.GraphListitem.self,
    "app.bsky.graph.referencelistoptout": App.Bsky.GraphReferencelistoptout.self,
    "app.bsky.graph.starterpack": App.Bsky.GraphStarterpack.self,
    "app.bsky.graph.verification": App.Bsky.GraphVerification.self,
    "app.bsky.labeler.service": App.Bsky.LabelerService.self,
    "app.bsky.notification.declaration": App.Bsky.NotificationDeclaration.self,
    "chat.bsky.actor.declaration": Chat.Bsky.ActorDeclaration.self,
    "com.atproto.lexicon.schema": Com.Atproto.LexiconSchema.self,
    "com.germnetwork.declaration": Com.Germnetwork.Declaration.self,
  ]

  public var type: Swift.String? {
    switch self {
    case .record(let record):
      return Swift.type(of: record).nsId
    case .any:
      return nil
    }
  }

  public var val: any Codable & Hashable & Sendable {
    switch self {
    case .record(let record):
      record
    case .any(let object):
      object
    }
  }
}
