import Foundation
import Testing

@testable import Moderation

/// Golden-file parity with the pinned TypeScript engine (@bsky/sdk@1.1.0).
///
/// The fixture is generated by `tools/golden-gen`; each case carries both the
/// serialized engine input and the engine's projected output. Every case must
/// reproduce the projection exactly, including per-context UI buckets.
@Suite struct ModerationGoldenTests {
  static let document: GoldenDocument = {
    do {
      let data = try Data(contentsOf: goldenFixtureURL())
      return try JSONDecoder().decode(GoldenDocument.self, from: data)
    } catch {
      fatalError("failed to load moderation golden fixture: \(error)")
    }
  }()

  @Test func fixtureHasExpectedShape() {
    #expect(Self.document.version == 1)
    #expect(Self.document.cases.count == 28)
  }

  @Test(arguments: [
    "clean-post",
    "content-label-porn-hide",
    "content-label-porn-warn",
    "content-label-porn-ignore",
    "adult-content-disabled-forces-hide",
    "labeler-not-configured-label-ignored",
    "account-label-porn-blurs-profile-surfaces",
    "muted-by-viewer",
    "blocking-by-viewer",
    "blocked-by-author",
    "muted-by-list",
    "blocking-by-list",
    "muted-word-content-match",
    "quote-post-muted-word-in-embed",
    "muted-word-no-match",
    "muted-word-exclude-following-follows-so-no-match",
    "hidden-post-filtered",
    "label-gore-default-hide",
    "unknown-label-value-ignored",
    "custom-labeler-definition",
    "custom-labeler-labeler-scoped-setting",
    "content-self-label-by-author",
    "is-me-own-account-label",
    "multiple-causes-priority-order",
    "profile-with-forced-hide-label",
    "user-list-with-label",
    "feed-generator-with-label",
    "downgrade-softens-blur-to-inform",
  ])
  func goldenCase(_ name: String) throws {
    let goldenCase = try #require(Self.document.cases.first { $0.name == name })
    let initialDecision = goldenCase.input.makeDecision()
    if let expected = goldenCase.expected.single {
      let actual = projectDecision(initialDecision)
      #expect(actual == expected, "case \(name) did not match the golden projection")
      return
    }
    let before = try #require(goldenCase.expected.before)
    let afterDowngrade = try #require(goldenCase.expected.afterDowngrade)
    var decision = initialDecision
    #expect(projectDecision(decision) == before, "case \(name) before downgrade")
    decision.downgrade()
    #expect(projectDecision(decision) == afterDowngrade, "case \(name) after downgrade")
  }
}
